[#149500259]: modification to dataset matching endpoint
Crunch-io/apidocs pull request #130
Opened 2017-07-25 23:42 UTC by percious

2017-08-02 22:20 UTC, jjdelc commented on source/includes/_endpoint-dataset.md
> +POST /datasets/match HTTP/1.1
This needs the trailing slash, else cherrypy will 301 on it if someone was to follow this example

2017-08-02 22:38 UTC, jjdelc requested changes

2017-08-02 22:38 UTC, jjdelc commented on source/includes/_endpoint-dataset.md
> +```http
This needs a bit more information. The controller sets a Location header somewhere, and the endpoint can return 201 or 202 sometimes. It is not specified when should one expect such response and what to do on each case

2017-08-02 22:38 UTC, jjdelc commented on source/includes/_endpoint-dataset.md
> +POST /datasets/match HTTP/1.1
This needs the trailing slash, else cherrypy will 301 on it if someone was to follow this example

2017-08-02 22:38 UTC, jjdelc commented on source/includes/_endpoint-dataset.md
> +                [
Is this a list of lists? 

A `shoji:order` graph doesn't really allow for this, inside a list it allows for dicts (as groups) and single elements (usually strings/urls).

The response here looks very ad-hoc and seems much better suited for a `shoji:view` where you have truly free form and the order can be respected if it's documented as so.

2017-08-04 16:22 UTC, percious commented on source/includes/_endpoint-dataset.md
> +                [
i'm fine with switching this to a view in the context of another ticket since we will have to change whaam not to use "graph" any more.

2017-08-04 20:11 UTC, jjdelc commented on source/includes/_endpoint-dataset.md
> +                [
Please also add this change to that ticket:
https://github.com/Crunch-io/backend-http/pull/728/files#diff-ebceaf08643a7a452d686bf57136b7e8R121 should be shoji:entities

2017-08-08 04:11 UTC, merged