Docs for the new blank_missings option
Crunch-io/apidocs pull request #83
Opened 2017-02-24 22:27 UTC by jjdelc

2017-02-27 19:28 UTC, nealrichardson commented on source/includes/_endpoint-dataset.md
> +Format    | Attribute           | Description                                                                         | Example
Much more useful than "Example" would be "Default".

2017-02-28 17:25 UTC, nealrichardson commented on source/includes/_endpoint-dataset.md
> +spss      | prefix_subvariables | When True, will only export subvariables and not group them as arrays               | {"prefix_subvariables": true}
The "not group them as arrays" is inaccurate, right?

2017-02-28 17:32 UTC, jjdelc commented on source/includes/_endpoint-dataset.md
> +spss      | prefix_subvariables | When True, will only export subvariables and not group them as arrays               | {"prefix_subvariables": true}
True, we changed it to only prefix the names

2017-02-28 19:35 UTC, nealrichardson commented on source/includes/_endpoint-dataset.md
> +csv       | missing_values      | Which value to use for printing missing values; allowed "dot", "reason", "blank"    | {"missing_values": "reason}
missing a close "

2017-02-28 19:36 UTC, nealrichardson commented on source/includes/_endpoint-dataset.md
> +csv       | missing_values      | Which value to use for printing missing values; allowed "dot", "reason", "blank"    | {"missing_values": "reason}
And why not just give the value instead of `{key: value}` for the defaults? Seems redundant.

2017-02-28 19:41 UTC, nealrichardson commented on source/includes/_endpoint-dataset.md
> +csv       | missing_values      | Which value to use for printing missing values; allowed "dot", "reason", "blank"    | {"missing_values": "reason}
Why not just use "" for "blank" and "." for "dot"? That way you can take any user specified string (that isn't "reason") and use that.

2017-02-28 20:12 UTC, jjdelc commented on source/includes/_endpoint-dataset.md
> +csv       | missing_values      | Which value to use for printing missing values; allowed "dot", "reason", "blank"    | {"missing_values": "reason}
"" is too falsey, I prefer the more explicit option. Cannot be confused with "forgot value" case.

2017-02-28 21:27 UTC, nealrichardson commented on source/includes/_endpoint-dataset.md
> +csv       | missing_values      | Which value to use for printing missing values; allowed "dot", "reason", "blank"    | {"missing_values": "reason}
I disagree that "" is too falsey, particularly when this field has no boolean meaning. And I don't know what "forgot value" means--if I truly forgot to specify a value, this wouldn't be here at all. 

I naturally have R in mind when I suggest the direct string input. See the 'na' argument to https://stat.ethz.ch/R-manual/R-devel/library/utils/html/write.table.html, which is what writes CSVs in R.

2017-03-02 18:14 UTC, percious requested changes

2017-03-02 18:14 UTC, percious commented on source/includes/_endpoint-dataset.md
can you describe "blank" and "dot" here?

2017-03-02 18:17 UTC, nealrichardson commented on source/includes/_endpoint-dataset.md
"blank" and "dot" don't exist anymore.

2017-03-02 23:17 UTC, jjdelc commented on source/includes/_endpoint-dataset.md
Is this from an outdated version? The current content of the text describes, whatever string you send will be used.

2017-03-04 03:02 UTC, merged